apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: default
spec:
  type: NodePort
  selector:
    app: logstash
  ports:
    - name: beats
      protocol: TCP
      port: 5044
      targetPort: 5044
      nodePort: 30544
    - name: monitoring
      protocol: TCP
      port: 9600
      targetPort: 9600
      nodePort: 30960
