apiVersion: v1
kind: Secret
metadata:
  name: keycloak-pg-secret
type: Opaque
data:
  DB_USER: a2V5Y2xvYWt1c2Vy   # base64 for 'keycloakuser'
  DB_PASSWORD: eW91clN0cm9uZ1Bhc3N3b3Jk   # base64 for 'yourStrongPassword'
