apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-1
        image: nginx:latest
        ports:
        - containerPort: 80
      - name: nginx-2
        image: nginx:latest
        ports:
        - containerPort: 81
